### ISSUE TITLE
Migrating from MakeMe to Cura

### ISSUE THREAD

**Issue by stephenyeargin** [tchapi/CuraForMakerbots#2]
With this profile loaded, we ran into some trouble with the extrusion rate. The filament feed does not appear to be fast enough for the Replicator 2, causing it to bake and clog in the extruder head.

We're attempting to make it match a known-good configuration from MakeMe -- https://github.com/make-me/make-me/blob/master/config/grue-default.config

Any tips?

/cc @jfryman @jameswhite

**Comment by jameswhite** [comment]
The extrusion rate is just the theory I came up with because during a larger print, there starts to be gaps in the in-fill, and then it just stops and clogs.

**Comment by tchapi** [comment]
Hi,
I don't think extrusion rate is your problem since it would fail from the start if it was — not enough filament would flow and the gaps would be present from the first layer onwards. So the problem lies somewhere else.

I work with Replicator 2's, and to me this is more a heating problem. Could be that your layer height is two small (0.15 in this profile, 0.27 in the make me profile you linked), or maybe that the retraction parameters are not adapted. You could try these parameters (in the `ini` file) to see if it works better :

```
retraction_min_travel = 1.0
retraction_speed = 20.0
retraction_amount = 1
```

Apart from that, I cannot really help you since it really depends on the models, your machine settings, etc. Gaps during long prints can also generally boil down to a more technical problem with the fan (the one that cools the bar mount) — it may blow in the wrong direction or miss blades.

Best

**Comment by stephenyeargin** [comment]
Thanks for the tips! We'll give these a spin and report back.
